[project]
name = "repl-nix-new-repl-1"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.0",
    "pygame>=2.6.1",
    "scipy>=1.14.1",
    "sounddevice>=0.5.1",
]
